name: py3.14
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - beautifulsoup4=4.14.2=pyha770c72_0
  - brotli-python=1.2.0=py314hdfeb8a1_0
  - bs4=4.14.2=hd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py314h4a8dc5f_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh707e725_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - ld_impl_linux-64=2.45=h1aa0949_0
  - libblas=3.11.0=2_h4a7cf45_openblas
  - libcblas=3.11.0=2_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - liblapack=3.11.0=2_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.0=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libuuid=2.41.2=he9a06e4_0
  - libxml2=2.15.1=h031cc0b_0
  - libxml2-16=2.15.1=hf2a90c1_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lxml=6.0.2=py314hae3bed6_2
  - ncurses=6.5=h2d0b736_3
  - numpy=2.3.5=py314h2b28147_0
  - openssl=3.6.0=h26f9b46_0
  - pandas=2.3.3=py314ha0b5721_1
  - pip=25.3=pyh145f28c_0
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.0=h32b2ec7_102_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-docx=1.2.0=pyhff2d567_0
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-dotenv-with-cli=1.2.1=h1ec61ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - six=1.17.0=pyhe01879c_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py314h0f05182_1
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/gt293/miniconda3/envs/py3.14
